In [1]:
import sys
import numpy as np
import cmapPy.pandasGEXpress.parse_gctx

In [2]:
information_data = cmapPy.pandasGEXpress.parse_gctx.parse('./bgedv2_QNORM.gctx',
                                                              convert_neg_666=True, ridx=None, cidx=None,
                                                              row_meta_only=False,
                                                              col_meta_only=False, make_multiindex=False)

/home/liusai/miniconda3/envs/L1000/lib/python3.9/site-packages/cmapPy/pandasGEXpress/parse_gctx.py:275: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  meta_df = meta_df.apply(lambda x: pd.to_numeric(x, errors="ignore"))
/home/liusai/miniconda3/envs/L1000/lib/python3.9/site-packages/cmapPy/pandasGEXpress/parse_gctx.py:275: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  meta_df = meta_df.apply(lambda x: pd.to_numeric(x, errors="ignore"))

In [ ]:
full_data_df = information_data.data_df

In [5]:
first_column = information_data.data_df.iloc[:, 0]
print(first_column)

rid
217398_x_at        14.8059
1007_s_at           9.1706
121_at              7.9557
200045_at          10.0987
200053_at           9.3033
                    ...
AFFX-ThrX-5_at      4.5785
AFFX-ThrX-M_at      4.5270
AFFX-TrpnX-3_at     4.2853
AFFX-TrpnX-5_at     4.6450
AFFX-TrpnX-M_at     4.2855
Name: BSM_0001_PRE-B-I, Length: 22268, dtype: float32

In [7]:
import pandas as pd

In [ ]:
data = pd.read_csv("data11.csv")

In [12]:
subset_rows = information_data.data_df.loc[data['ID']]

In [13]:
data.iloc[:, 3:]

,CBD_V1,CBD_V2,CBD_V3,CBD_V4,CBD_V5,CBD_V6,CBD_V7,CBD_V8,CBD_V9,CBD_V10,...,DMSO_CBD_V26,DMSO_CBD_V27,DMSO_CBD_V28,DMSO_CBD_V29,DMSO_CBD_V30,DMSO_CBD_V31,DMSO_CBD_V32,DMSO_CBD_V33,DMSO_CBD_V34,DMSO_CBD_V35
0,-0.476034,-0.433765,-0.374470,-0.357422,-0.406307,-0.446128,-0.380997,-0.385376,-0.516110,-0.443773,...,-0.368013,-0.437781,-0.366960,-0.359281,-0.344014,-0.415955,-0.366983,-0.357459,-0.386385,-0.325921
449,0.564711,0.537275,0.408357,0.428139,0.620649,0.633780,0.550450,0.521671,0.537315,0.750715,...,0.453215,0.555891,0.560080,0.553944,0.529272,0.509657,0.501611,0.513405,0.507363,0.488739
538,-0.299119,0.028007,-0.460225,-0.201495,-0.564722,-0.571420,-0.489416,-0.468736,0.094864,0.300155,...,-0.480849,-0.582972,0.161073,-0.536573,-0.551774,0.018228,-0.510690,-0.238868,-0.455512,-0.110657
608,-0.714248,-0.728480,-0.679923,-0.856994,-0.770679,-0.748135,-0.752283,-0.728583,-0.728207,-0.775026,...,-0.706688,-0.750824,-0.621205,-0.735527,-0.747516,-0.723175,-0.711872,-0.825964,-0.788404,-0.589623
700,-0.200185,-0.178877,-0.180982,-0.245086,-0.131687,-0.271931,-0.065266,-0.232794,-0.308150,-0.272732,...,-0.270012,-0.092723,-0.200473,-0.250114,-0.265102,-0.299193,-0.310606,-0.283891,-0.279312,-0.153156
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253,0.975558,0.565112,1.051065,0.912857,0.615458,0.752244,0.826992,0.726351,0.726353,0.206213,...,0.782354,0.851722,0.633193,0.783262,0.882290,0.617240,0.866357,0.638424,0.697507,0.686561
255,-0.798402,-0.837949,-0.830857,-0.881715,-0.888194,-0.863740,-0.817429,-0.852343,-0.814242,-0.828844,...,-0.893234,-0.842538,-0.778458,-0.874320,-0.883140,-0.761437,-0.858955,-0.873272,-0.881090,-0.745566
258,-0.419353,-0.376749,-0.439105,-0.310800,-0.204524,-0.404282,-0.344365,-0.484925,-0.495345,-0.515594,...,-0.359826,-0.301190,-0.637124,-0.302355,-0.380849,-0.664835,-0.499810,-0.368428,-0.397131,-0.598852
259,-0.231428,-0.387802,-0.204659,-0.375059,-0.322567,-0.333178,-0.400297,-0.451314,-0.289370,-0.357121,...,-0.301914,-0.327385,-0.382672,-0.301617,-0.291288,-0.291992,-0.253867,-0.377909,-0.305335,-0.403686
261,-0.895842,-0.897791,-0.799331,-0.952745,-0.892595,-0.843122,-0.745088,-0.867980,-0.704577,-0.875962,...,-0.860423,-0.884913,-0.705348,-0.884176,-0.817013,-0.688406,-0.784676,-0.950119,-0.870705,-0.752013

In [14]:
data_sub = data.iloc[:, 5:]
data_sub

,CBD_V3,CBD_V4,CBD_V5,CBD_V6,CBD_V7,CBD_V8,CBD_V9,CBD_V10,CBD_V11,CBD_V12,...,DMSO_CBD_V26,DMSO_CBD_V27,DMSO_CBD_V28,DMSO_CBD_V29,DMSO_CBD_V30,DMSO_CBD_V31,DMSO_CBD_V32,DMSO_CBD_V33,DMSO_CBD_V34,DMSO_CBD_V35
0,-0.374470,-0.357422,-0.406307,-0.446128,-0.380997,-0.385376,-0.516110,-0.443773,-0.405095,-0.398393,...,-0.368013,-0.437781,-0.366960,-0.359281,-0.344014,-0.415955,-0.366983,-0.357459,-0.386385,-0.325921
449,0.408357,0.428139,0.620649,0.633780,0.550450,0.521671,0.537315,0.750715,0.688374,0.594573,...,0.453215,0.555891,0.560080,0.553944,0.529272,0.509657,0.501611,0.513405,0.507363,0.488739
538,-0.460225,-0.201495,-0.564722,-0.571420,-0.489416,-0.468736,0.094864,0.300155,-0.657580,-0.321829,...,-0.480849,-0.582972,0.161073,-0.536573,-0.551774,0.018228,-0.510690,-0.238868,-0.455512,-0.110657
608,-0.679923,-0.856994,-0.770679,-0.748135,-0.752283,-0.728583,-0.728207,-0.775026,-0.716088,-0.823889,...,-0.706688,-0.750824,-0.621205,-0.735527,-0.747516,-0.723175,-0.711872,-0.825964,-0.788404,-0.589623
700,-0.180982,-0.245086,-0.131687,-0.271931,-0.065266,-0.232794,-0.308150,-0.272732,-0.265779,-0.161696,...,-0.270012,-0.092723,-0.200473,-0.250114,-0.265102,-0.299193,-0.310606,-0.283891,-0.279312,-0.153156
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253,1.051065,0.912857,0.615458,0.752244,0.826992,0.726351,0.726353,0.206213,0.856275,0.744401,...,0.782354,0.851722,0.633193,0.783262,0.882290,0.617240,0.866357,0.638424,0.697507,0.686561
255,-0.830857,-0.881715,-0.888194,-0.863740,-0.817429,-0.852343,-0.814242,-0.828844,-0.846061,-0.843119,...,-0.893234,-0.842538,-0.778458,-0.874320,-0.883140,-0.761437,-0.858955,-0.873272,-0.881090,-0.745566
258,-0.439105,-0.310800,-0.204524,-0.404282,-0.344365,-0.484925,-0.495345,-0.515594,-0.407500,-0.453787,...,-0.359826,-0.301190,-0.637124,-0.302355,-0.380849,-0.664835,-0.499810,-0.368428,-0.397131,-0.598852
259,-0.204659,-0.375059,-0.322567,-0.333178,-0.400297,-0.451314,-0.289370,-0.357121,-0.276142,-0.327751,...,-0.301914,-0.327385,-0.382672,-0.301617,-0.291288,-0.291992,-0.253867,-0.377909,-0.305335,-0.403686
261,-0.799331,-0.952745,-0.892595,-0.843122,-0.745088,-0.867980,-0.704577,-0.875962,-0.799030,-0.868935,...,-0.860423,-0.884913,-0.705348,-0.884176,-0.817013,-0.688406,-0.784676,-0.950119,-0.870705,-0.752013

In [15]:
subset_rows

cid,BSM_0001_PRE-B-I,BSM_0001_PRE-B-I_1,BSM_0002_IMMATURE,BSM_0002_IMMATURE_1,BSM_0003_PRE-B-IISMALL,BSM_0005_IMMATURE,BSM_0007_PRE-B-I,BSM_0008_PRE-B-IISMALL,BSM_0011_NCB,BSM_0014_NCB,...,BSM_S0158-138-10,BSM_S0158-139-11,BSM_S0158-140-12,BSM_S0158-141-14,BSM_JOS2634,BSM_JOS2724,BSM_JOS2798,BSM_JOS2914,BSM_JOS2915,BSM_JOS2924
rid,,,,,,,,,,,,,,,,,,,,,
213453_x_at,14.7519,14.7519,14.7608,14.7608,13.9897,14.1748,14.8005,14.5327,14.7542,14.8023,...,14.8179,14.8077,14.7950,14.8095,8.8852,8.1838,10.0000,9.2990,5.5936,9.1872
200045_at,10.0987,10.0987,10.6225,10.6225,9.9195,10.4877,10.1641,10.3081,10.2790,10.7614,...,9.3493,9.2248,9.5497,9.4171,10.0392,8.5493,8.2837,10.0812,9.5710,8.9691
200053_at,9.3033,9.3033,10.2948,10.2948,10.4197,9.5520,9.7014,9.6120,9.7832,10.2261,...,8.7357,8.6118,8.6466,8.7649,10.5337,8.5523,7.7274,10.9363,8.5157,8.1450
200071_at,10.9609,10.9609,10.2436,10.2436,10.9548,9.5983,9.4229,8.3968,10.9983,8.3551,...,10.7224,10.8375,11.3762,10.5324,6.9178,10.7898,10.7252,7.6479,7.3645,9.8277
200078_s_at,11.9825,11.9825,11.9902,11.9902,12.7926,12.0416,11.6512,11.1744,10.3773,10.5060,...,10.4729,10.3749,10.3138,10.4705,9.9535,8.6882,8.4245,9.0020,9.9100,8.1663
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40420_at,8.6855,8.6855,8.3604,8.3604,8.6412,9.3287,9.2457,9.3521,8.6339,9.8971,...,6.5039,6.3845,6.7499,6.4021,8.3018,7.0611,7.0060,7.7008,7.1387,6.5671
41329_at,6.1361,6.1361,5.7060,5.7060,5.9400,6.8230,6.9493,6.3951,7.0057,6.0003,...,6.6305,6.6271,6.2998,6.6155,8.1239,7.6655,7.7492,5.6615,10.1799,8.1641
57540_at,5.5425,5.5425,4.8663,4.8663,4.8627,5.6140,5.9978,5.8700,5.4522,5.0443,...,7.2880,7.2910,6.8812,7.1090,10.0894,7.3468,7.8811,8.6487,6.7512,8.2458
58696_at,5.7160,5.7160,6.2520,6.2520,6.8496,7.6832,8.0171,8.3958,7.8827,8.5076,...,8.8724,8.8941,8.6061,8.9430,4.7564,6.3789,4.5723,7.0981,5.4119,6.7209
AFFX-HUMISGF3A/M97935_3_at,8.2795,8.2795,8.2643,8.2643,8.6797,8.7963,8.4098,7.8754,9.0155,7.7551,...,9.3579,9.2623,9.1905,9.2706,9.2596,10.0117,11.5133,7.9715,8.1287,9.6946

In [16]:
id_column2 = data['ID']

In [17]:
remaining_rows = information_data.data_df.drop(id_column2, axis=0, errors='ignore')

In [18]:
remaining_rows

cid,BSM_0001_PRE-B-I,BSM_0001_PRE-B-I_1,BSM_0002_IMMATURE,BSM_0002_IMMATURE_1,BSM_0003_PRE-B-IISMALL,BSM_0005_IMMATURE,BSM_0007_PRE-B-I,BSM_0008_PRE-B-IISMALL,BSM_0011_NCB,BSM_0014_NCB,...,BSM_S0158-138-10,BSM_S0158-139-11,BSM_S0158-140-12,BSM_S0158-141-14,BSM_JOS2634,BSM_JOS2724,BSM_JOS2798,BSM_JOS2914,BSM_JOS2915,BSM_JOS2924
rid,,,,,,,,,,,,,,,,,,,,,
217398_x_at,14.8059,14.8059,14.8277,14.8277,14.0744,14.4390,14.8616,14.4715,14.8261,14.8309,...,14.8229,14.8129,14.8005,14.8196,7.4424,7.9939,9.6896,9.5286,9.0812,9.2025
1007_s_at,9.1706,9.1706,7.8624,7.8624,8.7313,7.2827,8.9667,9.3775,6.5269,7.6437,...,7.1758,7.2237,7.5950,7.5757,13.9445,9.7406,9.7056,13.5666,13.4711,9.9844
121_at,7.9557,7.9557,8.4751,8.4751,8.2574,8.3646,8.2208,8.7237,8.8258,9.5184,...,6.7427,6.6418,6.8790,6.5553,11.5748,9.7397,8.9569,10.4389,10.4054,10.0481
200617_at,7.5098,7.5098,7.4879,7.4879,7.7250,9.1522,10.4925,9.0255,7.5405,8.5702,...,9.6812,9.7753,9.1384,9.6980,6.7575,5.5333,6.8455,7.0808,5.1134,7.7709
200636_s_at,5.5270,5.5270,5.2127,5.2127,4.9855,4.7743,4.8063,5.0398,5.4348,5.9035,...,9.9327,10.1651,9.8224,9.6922,10.9811,9.7338,9.3344,6.8337,6.3450,9.4371
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
AFFX-ThrX-5_at,4.5785,4.5785,4.2510,4.2510,4.2847,4.2297,4.2999,4.2281,4.2925,4.3951,...,4.3971,4.3293,4.3278,4.4767,4.4212,4.2036,4.7711,4.1513,4.1468,4.1959
AFFX-ThrX-M_at,4.5270,4.5270,4.7577,4.7577,4.2848,4.5087,4.2982,4.7965,4.4221,4.3500,...,4.3973,4.4905,4.3280,4.9808,5.4460,4.6807,4.5941,5.0919,4.1185,5.1509
AFFX-TrpnX-3_at,4.2853,4.2853,4.2511,4.2511,4.5996,4.2298,5.2227,4.7564,4.2926,4.1876,...,4.3974,4.3294,4.3567,4.3724,5.5781,4.3881,4.1927,4.1613,4.2743,4.6052
AFFX-TrpnX-5_at,4.6450,4.6450,4.2512,4.2512,4.6676,4.2299,4.7119,4.2282,4.2927,4.2518,...,4.9245,4.3295,4.9035,4.4131,5.7789,5.0963,5.0991,5.3533,4.4727,4.2012
AFFX-TrpnX-M_at,4.2855,4.2855,4.2513,4.2513,4.2849,4.2300,4.2983,4.2283,4.2928,4.1877,...,4.4227,4.3296,4.3281,4.3725,4.2094,4.8404,4.2728,5.2145,4.4593,4.7136

In [19]:
combined_df = pd.concat([subset_rows,subset_rows, remaining_rows], axis=0, ignore_index=False, keys=['subset_rows', 'subset_rows','remaining_rows'])

In [20]:
combined_df

cid                             BSM_0001_PRE-B-I  BSM_0001_PRE-B-I_1  \
               rid
subset_rows    213453_x_at               14.7519             14.7519
               200045_at                 10.0987             10.0987
               200053_at                  9.3033              9.3033
               200071_at                 10.9609             10.9609
               200078_s_at               11.9825             11.9825
...                                          ...                 ...
remaining_rows AFFX-ThrX-5_at             4.5785              4.5785
               AFFX-ThrX-M_at             4.5270              4.5270
               AFFX-TrpnX-3_at            4.2853              4.2853
               AFFX-TrpnX-5_at            4.6450              4.6450
               AFFX-TrpnX-M_at            4.2855              4.2855

cid                             BSM_0002_IMMATURE  BSM_0002_IMMATURE_1  \
               rid
subset_rows    213453_x_at                14.7608              14.7608
               200045_at                  10.6225              10.6225
               200053_at                  10.2948              10.2948
               200071_at                  10.2436              10.2436
               200078_s_at                11.9902              11.9902
...                                           ...                  ...
remaining_rows AFFX-ThrX-5_at              4.2510               4.2510
               AFFX-ThrX-M_at              4.7577               4.7577
               AFFX-TrpnX-3_at             4.2511               4.2511
               AFFX-TrpnX-5_at             4.2512               4.2512
               AFFX-TrpnX-M_at             4.2513               4.2513

cid                             BSM_0003_PRE-B-IISMALL  BSM_0005_IMMATURE  \
               rid
subset_rows    213453_x_at                     13.9897            14.1748
               200045_at                        9.9195            10.4877
               200053_at                       10.4197             9.5520
               200071_at                       10.9548             9.5983
               200078_s_at                     12.7926            12.0416
...                                                ...                ...
remaining_rows AFFX-ThrX-5_at                   4.2847             4.2297
               AFFX-ThrX-M_at                   4.2848             4.5087
               AFFX-TrpnX-3_at                  4.5996             4.2298
               AFFX-TrpnX-5_at                  4.6676             4.2299
               AFFX-TrpnX-M_at                  4.2849             4.2300

cid                             BSM_0007_PRE-B-I  BSM_0008_PRE-B-IISMALL  \
               rid
subset_rows    213453_x_at               14.8005                 14.5327
               200045_at                 10.1641                 10.3081
               200053_at                  9.7014                  9.6120
               200071_at                  9.4229                  8.3968
               200078_s_at               11.6512                 11.1744
...                                          ...                     ...
remaining_rows AFFX-ThrX-5_at             4.2999                  4.2281
               AFFX-ThrX-M_at             4.2982                  4.7965
               AFFX-TrpnX-3_at            5.2227                  4.7564
               AFFX-TrpnX-5_at            4.7119                  4.2282
               AFFX-TrpnX-M_at            4.2983                  4.2283

cid                             BSM_0011_NCB  BSM_0014_NCB  ...  \
               rid                                          ...
subset_rows    213453_x_at           14.7542       14.8023  ...
               200045_at             10.2790       10.7614  ...
               200053_at              9.7832       10.2261  ...
               200071_at             10.9983        8.3551  ...
               200078_s_at           10.3773       10.5060  ...
...                                      ...           ...  ...
remaining_rows AFFX-ThrX-5_at         4.2925        4.3951  ...
               AFFX-ThrX-M_at         4.4221        4.3500  ...
               AFFX-TrpnX-3_at        4.2926        4.1876  ...
               AFFX-TrpnX-5_at        4.2927        4.2518  ...
               AFFX-TrpnX-M_at        4.2928        4.1877  ...

cid                             BSM_S0158-138-10  BSM_S0158-139-11  \
               rid
subset_rows    213453_x_at               14.8179           14.8077
               200045_at                  9.3493            9.2248
               200053_at                  8.7357            8.6118
               200071_at                 10.7224           10.8375
               200078_s_at               10.4729           10.3749
...                                          ...               ...
remaining_rows AFFX-ThrX-5_at             4.3971            4.3293
               AFFX-ThrX-M_at             4.3973            4.4905
               AFFX-TrpnX-3_at            4.3974            4.3294
               AFFX-TrpnX-5_at            4.9245            4.3295
               AFFX-TrpnX-M_at            4.4227            4.3296

cid                             BSM_S0158-140-12  BSM_S0158-141-14  \
               rid
subset_rows    213453_x_at               14.7950           14.8095
               200045_at                  9.5497            9.4171
               200053_at                  8.6466            8.7649
               200071_at                 11.3762           10.5324
               200078_s_at               10.3138           10.4705
...                                          ...               ...
remaining_rows AFFX-ThrX-5_at             4.3278            4.4767
               AFFX-ThrX-M_at             4.3280            4.9808
               AFFX-TrpnX-3_at            4.3567            4.3724
               AFFX-TrpnX-5_at            4.9035            4.4131
               AFFX-TrpnX-M_at            4.3281            4.3725

cid                             BSM_JOS2634  BSM_JOS2724  BSM_JOS2798  \
               rid
subset_rows    213453_x_at           8.8852       8.1838      10.0000
               200045_at            10.0392       8.5493       8.2837
               200053_at            10.5337       8.5523       7.7274
               200071_at             6.9178      10.7898      10.7252
               200078_s_at           9.9535       8.6882       8.4245
...                                     ...          ...          ...
remaining_rows AFFX-ThrX-5_at        4.4212       4.2036       4.7711
               AFFX-ThrX-M_at        5.4460       4.6807       4.5941
               AFFX-TrpnX-3_at       5.5781       4.3881       4.1927
               AFFX-TrpnX-5_at       5.7789       5.0963       5.0991
               AFFX-TrpnX-M_at       4.2094       4.8404       4.2728

cid                             BSM_JOS2914  BSM_JOS2915  BSM_JOS2924
               rid
subset_rows    213453_x_at           9.2990       5.5936       9.1872
               200045_at            10.0812       9.5710       8.9691
               200053_at            10.9363       8.5157       8.1450
               200071_at             7.6479       7.3645       9.8277
               200078_s_at           9.0020       9.9100       8.1663
...                                     ...          ...          ...
remaining_rows AFFX-ThrX-5_at        4.1513       4.1468       4.1959
               AFFX-ThrX-M_at        5.0919       4.1185       5.1509
               AFFX-TrpnX-3_at       4.1613       4.2743       4.6052
               AFFX-TrpnX-5_at       5.3533       4.4727       4.2012
               AFFX-TrpnX-M_at       5.2145       4.4593       4.7136

[23200 rows x 129158 columns]

In [21]:
df_transposed = combined_df.T

In [22]:
df_transposed

                       subset_rows                                            \
rid                    213453_x_at 200045_at 200053_at 200071_at 200078_s_at
cid
BSM_0001_PRE-B-I           14.7519   10.0987    9.3033   10.9609     11.9825
BSM_0001_PRE-B-I_1         14.7519   10.0987    9.3033   10.9609     11.9825
BSM_0002_IMMATURE          14.7608   10.6225   10.2948   10.2436     11.9902
BSM_0002_IMMATURE_1        14.7608   10.6225   10.2948   10.2436     11.9902
BSM_0003_PRE-B-IISMALL     13.9897    9.9195   10.4197   10.9548     12.7926
...                            ...       ...       ...       ...         ...
BSM_JOS2724                 8.1838    8.5493    8.5523   10.7898      8.6882
BSM_JOS2798                10.0000    8.2837    7.7274   10.7252      8.4245
BSM_JOS2914                 9.2990   10.0812   10.9363    7.6479      9.0020
BSM_JOS2915                 5.5936    9.5710    8.5157    7.3645      9.9100
BSM_JOS2924                 9.1872    8.9691    8.1450    9.8277      8.1663

                                                                            \
rid                    200083_at 200621_at 200670_at 200678_x_at 200697_at
cid
BSM_0001_PRE-B-I         12.3871    8.0431   12.3389      7.2346    8.8298
BSM_0001_PRE-B-I_1       12.3871    8.0431   12.3389      7.2346    8.8298
BSM_0002_IMMATURE        10.7984    9.2956    9.3153      9.0280    9.1614
BSM_0002_IMMATURE_1      10.7984    9.2956    9.3153      9.0280    9.1614
BSM_0003_PRE-B-IISMALL   11.3838    7.0570   10.2723      8.6872    8.1820
...                          ...       ...       ...         ...       ...
BSM_JOS2724               9.3435    8.4956   11.3259      6.2014    9.1866
BSM_JOS2798               9.4732    8.5754   12.3780      5.4473    9.0921
BSM_JOS2914              10.7060   10.6665    9.0578      7.9093    5.4997
BSM_JOS2915              10.3608   11.7965   10.3319      9.7115    9.2045
BSM_JOS2924               9.6854    8.4876   12.6532      5.8785    7.9483

                        ...       remaining_rows                       \
rid                     ... AFFX-r2-Ec-bioD-3_at AFFX-r2-Ec-bioD-5_at
cid                     ...
BSM_0001_PRE-B-I        ...               4.7895               4.2849
BSM_0001_PRE-B-I_1      ...               4.7895               4.2849
BSM_0002_IMMATURE       ...               4.6768               4.2507
BSM_0002_IMMATURE_1     ...               4.6768               4.2507
BSM_0003_PRE-B-IISMALL  ...               5.4943               4.2843
...                     ...                  ...                  ...
BSM_JOS2724             ...              13.9672              12.7632
BSM_JOS2798             ...              13.9166              13.6866
BSM_JOS2914             ...              14.9690              14.9610
BSM_JOS2915             ...              14.9767              14.9790
BSM_JOS2924             ...              14.7797              14.6965

                                                                               \
rid                    AFFX-r2-P1-cre-3_at AFFX-r2-P1-cre-5_at AFFX-ThrX-3_at
cid
BSM_0001_PRE-B-I                    4.2850              4.2851         4.2852
BSM_0001_PRE-B-I_1                  4.2850              4.2851         4.2852
BSM_0002_IMMATURE                   4.2508              4.2509         4.3711
BSM_0002_IMMATURE_1                 4.2508              4.2509         4.3711
BSM_0003_PRE-B-IISMALL              4.2844              4.2845         4.2846
...                                    ...                 ...            ...
BSM_JOS2724                        14.9726             14.9335         5.1971
BSM_JOS2798                        14.9767             14.9595         4.2278
BSM_JOS2914                        14.9845             14.9814         4.3463
BSM_JOS2915                        14.9845             14.9814         4.6429
BSM_JOS2924                        14.9552             14.9284         4.2412

                                                                      \
rid                    AFFX-ThrX-5_at AFFX-ThrX-M_at AFFX-TrpnX-3_at
cid
BSM_0001_PRE-B-I               4.5785         4.5270          4.2853
BSM_0001_PRE-B-I_1             4.5785         4.5270          4.2853
BSM_0002_IMMATURE              4.2510         4.7577          4.2511
BSM_0002_IMMATURE_1            4.2510         4.7577          4.2511
BSM_0003_PRE-B-IISMALL         4.2847         4.2848          4.5996
...                               ...            ...             ...
BSM_JOS2724                    4.2036         4.6807          4.3881
BSM_JOS2798                    4.7711         4.5941          4.1927
BSM_JOS2914                    4.1513         5.0919          4.1613
BSM_JOS2915                    4.1468         4.1185          4.2743
BSM_JOS2924                    4.1959         5.1509          4.6052


rid                    AFFX-TrpnX-5_at AFFX-TrpnX-M_at
cid
BSM_0001_PRE-B-I                4.6450          4.2855
BSM_0001_PRE-B-I_1              4.6450          4.2855
BSM_0002_IMMATURE               4.2512          4.2513
BSM_0002_IMMATURE_1             4.2512          4.2513
BSM_0003_PRE-B-IISMALL          4.6676          4.2849
...                                ...             ...
BSM_JOS2724                     5.0963          4.8404
BSM_JOS2798                     5.0991          4.2728
BSM_JOS2914                     5.3533          5.2145
BSM_JOS2915                     4.4727          4.4593
BSM_JOS2924                     4.2012          4.7136

[129158 rows x 23200 columns]

In [27]:
df_transposed_unique = df_transposed.drop_duplicates()

/tmp/ipykernel_5001/3786872763.py:1: PerformanceWarning: indexing past lexsort depth may impact performance.
  df_transposed_unique = df_transposed.drop_duplicates()

In [28]:
df_transposed_unique

                       subset_rows                                            \
rid                    213453_x_at 200045_at 200053_at 200071_at 200078_s_at
cid
BSM_0001_PRE-B-I           14.7519   10.0987    9.3033   10.9609     11.9825
BSM_0002_IMMATURE          14.7608   10.6225   10.2948   10.2436     11.9902
BSM_0003_PRE-B-IISMALL     13.9897    9.9195   10.4197   10.9548     12.7926
BSM_0005_IMMATURE          14.1748   10.4877    9.5520    9.5983     12.0416
BSM_0007_PRE-B-I           14.8005   10.1641    9.7014    9.4229     11.6512
...                            ...       ...       ...       ...         ...
BSM_JOS2724                 8.1838    8.5493    8.5523   10.7898      8.6882
BSM_JOS2798                10.0000    8.2837    7.7274   10.7252      8.4245
BSM_JOS2914                 9.2990   10.0812   10.9363    7.6479      9.0020
BSM_JOS2915                 5.5936    9.5710    8.5157    7.3645      9.9100
BSM_JOS2924                 9.1872    8.9691    8.1450    9.8277      8.1663

                                                                            \
rid                    200083_at 200621_at 200670_at 200678_x_at 200697_at
cid
BSM_0001_PRE-B-I         12.3871    8.0431   12.3389      7.2346    8.8298
BSM_0002_IMMATURE        10.7984    9.2956    9.3153      9.0280    9.1614
BSM_0003_PRE-B-IISMALL   11.3838    7.0570   10.2723      8.6872    8.1820
BSM_0005_IMMATURE        10.5324    8.4996    8.5233     10.9889    9.3550
BSM_0007_PRE-B-I         11.5356    8.2961   12.6223      8.6685    9.2623
...                          ...       ...       ...         ...       ...
BSM_JOS2724               9.3435    8.4956   11.3259      6.2014    9.1866
BSM_JOS2798               9.4732    8.5754   12.3780      5.4473    9.0921
BSM_JOS2914              10.7060   10.6665    9.0578      7.9093    5.4997
BSM_JOS2915              10.3608   11.7965   10.3319      9.7115    9.2045
BSM_JOS2924               9.6854    8.4876   12.6532      5.8785    7.9483

                        ...       remaining_rows                       \
rid                     ... AFFX-r2-Ec-bioD-3_at AFFX-r2-Ec-bioD-5_at
cid                     ...
BSM_0001_PRE-B-I        ...               4.7895               4.2849
BSM_0002_IMMATURE       ...               4.6768               4.2507
BSM_0003_PRE-B-IISMALL  ...               5.4943               4.2843
BSM_0005_IMMATURE       ...               4.8890               5.1212
BSM_0007_PRE-B-I        ...               4.2977               4.2978
...                     ...                  ...                  ...
BSM_JOS2724             ...              13.9672              12.7632
BSM_JOS2798             ...              13.9166              13.6866
BSM_JOS2914             ...              14.9690              14.9610
BSM_JOS2915             ...              14.9767              14.9790
BSM_JOS2924             ...              14.7797              14.6965

                                                                               \
rid                    AFFX-r2-P1-cre-3_at AFFX-r2-P1-cre-5_at AFFX-ThrX-3_at
cid
BSM_0001_PRE-B-I                    4.2850              4.2851         4.2852
BSM_0002_IMMATURE                   4.2508              4.2509         4.3711
BSM_0003_PRE-B-IISMALL              4.2844              4.2845         4.2846
BSM_0005_IMMATURE                   4.2295              4.2961         4.2296
BSM_0007_PRE-B-I                    4.2979              4.6460         4.2981
...                                    ...                 ...            ...
BSM_JOS2724                        14.9726             14.9335         5.1971
BSM_JOS2798                        14.9767             14.9595         4.2278
BSM_JOS2914                        14.9845             14.9814         4.3463
BSM_JOS2915                        14.9845             14.9814         4.6429
BSM_JOS2924                        14.9552             14.9284         4.2412

                                                                      \
rid                    AFFX-ThrX-5_at AFFX-ThrX-M_at AFFX-TrpnX-3_at
cid
BSM_0001_PRE-B-I               4.5785         4.5270          4.2853
BSM_0002_IMMATURE              4.2510         4.7577          4.2511
BSM_0003_PRE-B-IISMALL         4.2847         4.2848          4.5996
BSM_0005_IMMATURE              4.2297         4.5087          4.2298
BSM_0007_PRE-B-I               4.2999         4.2982          5.2227
...                               ...            ...             ...
BSM_JOS2724                    4.2036         4.6807          4.3881
BSM_JOS2798                    4.7711         4.5941          4.1927
BSM_JOS2914                    4.1513         5.0919          4.1613
BSM_JOS2915                    4.1468         4.1185          4.2743
BSM_JOS2924                    4.1959         5.1509          4.6052


rid                    AFFX-TrpnX-5_at AFFX-TrpnX-M_at
cid
BSM_0001_PRE-B-I                4.6450          4.2855
BSM_0002_IMMATURE               4.2512          4.2513
BSM_0003_PRE-B-IISMALL          4.6676          4.2849
BSM_0005_IMMATURE               4.2299          4.2300
BSM_0007_PRE-B-I                4.7119          4.2983
...                                ...             ...
BSM_JOS2724                     5.0963          4.8404
BSM_JOS2798                     5.0991          4.2728
BSM_JOS2914                     5.3533          5.2145
BSM_JOS2915                     4.4727          4.4593
BSM_JOS2924                     4.2012          4.7136

[114366 rows x 23200 columns]

In [23]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from scipy.stats import pearsonr
from sklearn.metrics import mean_squared_error, r2_score

In [29]:
df = pd.DataFrame(df_transposed_unique)

In [30]:
print(df.iloc[:, 0])

cid
BSM_0001_PRE-B-I          14.7519
BSM_0002_IMMATURE         14.7608
BSM_0003_PRE-B-IISMALL    13.9897
BSM_0005_IMMATURE         14.1748
BSM_0007_PRE-B-I          14.8005
                           ...
BSM_JOS2724                8.1838
BSM_JOS2798               10.0000
BSM_JOS2914                9.2990
BSM_JOS2915                5.5936
BSM_JOS2924                9.1872
Name: (subset_rows, 213453_x_at), Length: 114366, dtype: float32

In [31]:
X = df.iloc[:, :932] 
X

                       subset_rows                                            \
rid                    213453_x_at 200045_at 200053_at 200071_at 200078_s_at
cid
BSM_0001_PRE-B-I           14.7519   10.0987    9.3033   10.9609     11.9825
BSM_0002_IMMATURE          14.7608   10.6225   10.2948   10.2436     11.9902
BSM_0003_PRE-B-IISMALL     13.9897    9.9195   10.4197   10.9548     12.7926
BSM_0005_IMMATURE          14.1748   10.4877    9.5520    9.5983     12.0416
BSM_0007_PRE-B-I           14.8005   10.1641    9.7014    9.4229     11.6512
...                            ...       ...       ...       ...         ...
BSM_JOS2724                 8.1838    8.5493    8.5523   10.7898      8.6882
BSM_JOS2798                10.0000    8.2837    7.7274   10.7252      8.4245
BSM_JOS2914                 9.2990   10.0812   10.9363    7.6479      9.0020
BSM_JOS2915                 5.5936    9.5710    8.5157    7.3645      9.9100
BSM_JOS2924                 9.1872    8.9691    8.1450    9.8277      8.1663

                                                                            \
rid                    200083_at 200621_at 200670_at 200678_x_at 200697_at
cid
BSM_0001_PRE-B-I         12.3871    8.0431   12.3389      7.2346    8.8298
BSM_0002_IMMATURE        10.7984    9.2956    9.3153      9.0280    9.1614
BSM_0003_PRE-B-IISMALL   11.3838    7.0570   10.2723      8.6872    8.1820
BSM_0005_IMMATURE        10.5324    8.4996    8.5233     10.9889    9.3550
BSM_0007_PRE-B-I         11.5356    8.2961   12.6223      8.6685    9.2623
...                          ...       ...       ...         ...       ...
BSM_JOS2724               9.3435    8.4956   11.3259      6.2014    9.1866
BSM_JOS2798               9.4732    8.5754   12.3780      5.4473    9.0921
BSM_JOS2914              10.7060   10.6665    9.0578      7.9093    5.4997
BSM_JOS2915              10.3608   11.7965   10.3319      9.7115    9.2045
BSM_JOS2924               9.6854    8.4876   12.6532      5.8785    7.9483

                        ...                                             \
rid                     ... 221977_at 222015_at 222187_x_at 33322_i_at
cid                     ...
BSM_0001_PRE-B-I        ...    4.3834    5.2773      6.9590     8.9353
BSM_0002_IMMATURE       ...    4.2443    4.8131      6.9965    10.2348
BSM_0003_PRE-B-IISMALL  ...    4.2753    7.6713      6.7734     8.7633
BSM_0005_IMMATURE       ...    4.2238    4.5263      6.4147     8.5905
BSM_0007_PRE-B-I        ...    4.2889    4.9575      6.6188     8.0521
...                     ...       ...       ...         ...        ...
BSM_JOS2724             ...    4.1821    5.0810      6.9735    14.8892
BSM_JOS2798             ...    4.6504    4.7227      7.0090    13.4029
BSM_JOS2914             ...    4.4476    5.0760      9.3579    11.0690
BSM_JOS2915             ...    4.9608    4.8883      9.4446    13.8387
BSM_JOS2924             ...    4.2533    4.8496      6.7340     9.6511

                                                                     \
rid                    39402_at 40420_at 41329_at 57540_at 58696_at
cid
BSM_0001_PRE-B-I         6.7060   8.6855   6.1361   5.5425   5.7160
BSM_0002_IMMATURE        6.0814   8.3604   5.7060   4.8663   6.2520
BSM_0003_PRE-B-IISMALL   6.3739   8.6412   5.9400   4.8627   6.8496
BSM_0005_IMMATURE        5.5188   9.3287   6.8230   5.6140   7.6832
BSM_0007_PRE-B-I         8.6366   9.2457   6.9493   5.9978   8.0171
...                         ...      ...      ...      ...      ...
BSM_JOS2724              8.6647   7.0611   7.6655   7.3468   6.3789
BSM_JOS2798              7.3120   7.0060   7.7492   7.8811   4.5723
BSM_JOS2914              6.9053   7.7008   5.6615   8.6487   7.0981
BSM_JOS2915              8.1076   7.1387  10.1799   6.7512   5.4119
BSM_JOS2924              8.6076   6.5671   8.1641   8.2458   6.7209


rid                    AFFX-HUMISGF3A/M97935_3_at
cid
BSM_0001_PRE-B-I                           8.2795
BSM_0002_IMMATURE                          8.2643
BSM_0003_PRE-B-IISMALL                     8.6797
BSM_0005_IMMATURE                          8.7963
BSM_0007_PRE-B-I                           8.4098
...                                           ...
BSM_JOS2724                               10.0117
BSM_JOS2798                               11.5133
BSM_JOS2914                                7.9715
BSM_JOS2915                                8.1287
BSM_JOS2924                                9.6946

[114366 rows x 932 columns]

In [ ]:
X = df.iloc[:, :932]  
y = df.iloc[:, 932:]  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("回归系数:", model.coef_)
print("截距:", model.intercept_)


mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
print("均方误差 (MSE):", mse)
print("均方根误差 (RMSE):", rmse)
r2_s=r2_score(y_test, y_pred, multioutput='variance_weighted')
r2 = r2_score(y_test, y_pred)
print("R²:", r2)
print("R²_variance_weighted:", r2_s)
pearson_corrs = []
for i in range(y_test.shape[1]): 

    pearson_corr, _ = pearsonr(y_test.iloc[:, i], y_pred[:, i])
    pearson_corrs.append(pearson_corr)

average_pearson_corr = np.mean(pearson_corrs)
print(f"平均 Pearson 相关系数: {average_pearson_corr}")

回归系数: [[ 9.9999338e-01 -1.6426588e-06  1.1314121e-06 ... -8.0983682e-07
   1.7833902e-06 -6.0574689e-07]
 [-1.7475156e-06  1.0000001e+00  1.9017607e-06 ... -2.6077032e-08
   6.7800283e-07 -2.7148053e-07]
 [-2.6895807e-06  1.5087426e-06  1.0000041e+00 ... -2.9802322e-07
   4.1816384e-07  4.3213367e-07]
 ...
 [ 3.5682052e-02  2.8056867e-02  4.0398780e-03 ... -1.7302342e-02
   3.5828028e-02  4.2317182e-02]
 [ 3.8434550e-02  1.8782351e-02  4.2010676e-03 ... -7.5632520e-03
   4.1370966e-02  3.4662321e-02]
 [ 4.1234691e-02  3.1091060e-02 -1.3988227e-02 ...  1.6521801e-03
   3.3505000e-02  3.0770518e-02]]
截距: [2.3460388e-04 4.4822693e-05 1.0967255e-04 ... 2.1514835e+01 1.9484272e+01
 2.0814995e+01]
均方误差 (MSE): 0.37597173
均方根误差 (RMSE): 0.6131653
R²: 0.6608542203903198
R²_variance_weighted: 0.7537636160850525
平均 Pearson 相关系数: 0.8048144067398764

In [ ]:
#######################
#######################
#######################part2
data = pd.read_csv("data11.csv")

In [77]:
data.sort_values(by='id', ascending=True, inplace=True)

In [78]:
data

,Unnamed: 0,Row.names,Gene.Symbol,ID,id,V12CBD,V15CBD,V59CBD,V75CBD,V77CBD,...,V99CBD,V100CBD,V12DMSO,V15DMSO,V59DMSO,V75DMSO,V77DMSO,V96DMSO,V99DMSO,V100DMSO
0,316,GAPDH,GAPDH,213453_x_at,1,-0.441694,-0.484454,-0.433886,-0.430053,-0.463378,...,-0.463216,-0.385556,-0.418532,-0.488771,-0.432547,-0.448711,-0.427622,-0.421336,-0.425136,-0.417278
1,4,ABCF1,ABCF1,200045_at,4,0.714606,0.634927,0.676245,0.617852,0.671104,...,0.733470,0.459241,0.686180,0.649902,0.679958,0.651573,0.664913,0.642512,0.647600,0.650291
2,780,SPAG7,SPAG7,200053_at,5,-0.252455,-0.456084,-0.354450,-0.621162,-0.220649,...,-0.401284,0.540668,-0.168602,-0.516720,-0.221221,-0.430325,-0.150338,-0.166023,-0.153687,-0.081812
3,768,SMNDC1,SMNDC1,200071_at,6,-0.698006,-0.747004,-0.732276,-0.723635,-0.812894,...,-0.685755,-0.553625,-0.683280,-0.741657,-0.692660,-0.702486,-0.674849,-0.664535,-0.674022,-0.661928
4,57,ATP6V0B,ATP6V0B,200078_s_at,7,-0.121489,-0.118030,-0.067767,-0.185876,-0.181127,...,-0.116660,-0.190350,-0.111069,-0.171846,-0.071897,-0.134777,-0.121387,-0.115640,-0.109129,-0.142228
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
927,798,STK10,STK10,40420_at,21965,0.455246,0.788010,0.499767,0.743298,0.385805,...,0.438203,0.636703,0.420372,1.052213,0.460744,0.622023,0.450414,0.445288,0.425279,0.446419
928,735,SCYL3,SCYL3,41329_at,21983,-0.806654,-0.861559,-0.832930,-0.864376,-0.830376,...,-0.802384,-0.841154,-0.785771,-0.894276,-0.799942,-0.821542,-0.782501,-0.780172,-0.776929,-0.793012
929,691,RBKS,RBKS,57540_at,22125,-0.456271,-0.109910,-0.282153,-0.182146,-0.392441,...,-0.294021,-0.424055,-0.449246,-0.084142,-0.379429,-0.272515,-0.423555,-0.436325,-0.425256,-0.433765
930,276,EXOSC4,EXOSC4,58696_at,22131,-0.459923,-0.252345,-0.325600,-0.290499,-0.386760,...,-0.445373,-0.380434,-0.434901,-0.102448,-0.391427,-0.325013,-0.430252,-0.412542,-0.430450,-0.419433
931,795,STAT1,STAT1,AFFX-HUMISGF3A/M97935_3_at,22226,-0.801339,-0.888362,-0.840314,-0.897849,-0.812856,...,-0.843670,-0.730314,-0.779772,-0.946178,-0.797830,-0.814017,-0.774548,-0.758160,-0.766335,-0.785286

In [79]:
data2 = data.T

In [80]:
data2

,0,1,2,3,4,5,6,7,8,9,...,922,923,924,925,926,927,928,929,930,931
Unnamed: 0,316,4,780,768,57,900,192,916,340,357,...,819,190,310,740,397,798,735,691,276,795
Row.names,GAPDH,ABCF1,SPAG7,SMNDC1,ATP6V0B,USP22,CSRP1,XBP1,GRN,HK1,...,TBX2,CSNK1E,G3BP1,SFN,IL1B,STK10,SCYL3,RBKS,EXOSC4,STAT1
Gene.Symbol,GAPDH,ABCF1,SPAG7,SMNDC1,ATP6V0B,USP22,CSRP1,XBP1,GRN,HK1,...,TBX2,CSNK1E,G3BP1,SFN,IL1B,STK10,SCYL3,RBKS,EXOSC4,STAT1
ID,213453_x_at,200045_at,200053_at,200071_at,200078_s_at,200083_at,200621_at,200670_at,200678_x_at,200697_at,...,221977_at,222015_at,222187_x_at,33322_i_at,39402_at,40420_at,41329_at,57540_at,58696_at,AFFX-HUMISGF3A/M97935_3_at
id,1,4,5,6,7,8,10,13,14,15,...,21356,21394,21564,21799,21940,21965,21983,22125,22131,22226
V12CBD,-0.441694,0.714606,-0.252455,-0.698006,-0.121489,1.791759,0.563874,0.216976,0.496316,1.302225,...,-0.144415,-0.357333,0.696582,-0.406239,-0.594995,0.455246,-0.806654,-0.456271,-0.459923,-0.801339
V15CBD,-0.484454,0.634927,-0.456084,-0.747004,-0.11803,2.183244,0.292293,0.005546,0.482427,1.301236,...,-0.19557,-0.2182,0.890093,-0.538219,-0.681348,0.78801,-0.861559,-0.10991,-0.252345,-0.888362
V59CBD,-0.433886,0.676245,-0.35445,-0.732276,-0.067767,2.447251,0.513434,-0.05507,0.519604,1.091963,...,-0.142337,-0.244578,0.875527,-0.620314,-0.614889,0.499767,-0.83293,-0.282153,-0.3256,-0.840314
V75CBD,-0.430053,0.617852,-0.621162,-0.723635,-0.185876,2.230853,0.119042,-0.190244,0.378296,0.896653,...,-0.170078,-0.257523,1.084113,-0.622394,-0.636057,0.743298,-0.864376,-0.182146,-0.290499,-0.897849
V77CBD,-0.463378,0.671104,-0.220649,-0.812894,-0.181127,2.063128,0.704712,0.135509,0.330133,1.244117,...,-0.173842,-0.240286,0.895598,-0.64339,-0.598937,0.385805,-0.830376,-0.392441,-0.38676,-0.812856
V96CBD,-0.363495,0.618154,-0.240221,-0.683399,-0.171871,2.296653,0.315205,-0.027883,0.388409,1.084987,...,-0.17252,-0.266806,0.851603,-0.567453,-0.623087,0.556548,-0.82959,-0.358175,-0.354244,-0.817816
V99CBD,-0.463216,0.73347,-0.401284,-0.685755,-0.11666,1.503171,0.365917,-0.106233,0.583055,1.391821,...,-0.228818,-0.435935,0.665364,-0.333447,-0.674632,0.438203,-0.802384,-0.294021,-0.445373,-0.84367
V100CBD,-0.385556,0.459241,0.540668,-0.553625,-0.19035,2.566788,0.883203,0.329547,0.396038,1.403423,...,-0.170481,-0.522289,0.898696,-0.370671,-0.700212,0.636703,-0.841154,-0.424055,-0.380434,-0.730314
V12DMSO,-0.418532,0.68618,-0.168602,-0.68328,-0.111069,1.735999,0.568176,0.157265,0.473853,1.451995,...,-0.174411,-0.272481,0.624036,-0.378707,-0.532824,0.420372,-0.785771,-0.449246,-0.434901,-0.779772
V15DMSO,-0.488771,0.649902,-0.51672,-0.741657,-0.171846,2.418734,0.24238,0.004106,0.525163,1.230885,...,-0.195447,-0.146278,1.140006,-0.664448,-0.772246,1.052213,-0.894276,-0.084142,-0.102448,-0.946178
V59DMSO,-0.432547,0.679958,-0.221221,-0.69266,-0.071897,1.908806,0.564367,0.018475,0.534427,1.334628,...,-0.183095,-0.25327,0.652324,-0.441856,-0.54627,0.460744,-0.799942,-0.379429,-0.391427,-0.79783
V75DMSO,-0.448711,0.651573,-0.430325,-0.702486,-0.134777,2.012751,0.291894,0.01241,0.448259,1.305088,...,-0.202911,-0.23811,0.768273,-0.490875,-0.590364,0.622023,-0.821542,-0.272515,-0.325013,-0.814017
V77DMSO,-0.427622,0.664913,-0.150338,-0.674849,-0.121387,1.839942,0.482421,0.009606,0.487649,1.331234,...,-0.177426,-0.269186,0.653342,-0.35218,-0.527622,0.450414,-0.782501,-0.423555,-0.430252,-0.774548
V96DMSO,-0.421336,0.642512,-0.166023,-0.664535,-0.11564,1.819769,0.522553,0.152318,0.481725,1.497902,...,-0.183236,-0.251215,0.614042,-0.372539,-0.524366,0.445288,-0.780172,-0.436325,-0.412542,-0.75816
V99DMSO,-0.425136,0.6476,-0.153687,-0.674022,-0.109129,1.761637,0.527055,0.151553,0.485571,1.492487,...,-0.215679,-0.251467,0.636113,-0.376489,-0.539423,0.425279,-0.776929,-0.425256,-0.43045,-0.766335
V100DMSO,-0.417278,0.650291,-0.081812,-0.661928,-0.142228,1.749156,0.662269,0.235985,0.420544,1.282202,...,-0.118409,-0.267439,0.645533,-0.401672,-0.51948,0.446419,-0.793012,-0.433765,-0.419433,-0.785286

In [82]:
data3= data2.iloc[5:,:]

In [83]:
data3

,0,1,2,3,4,5,6,7,8,9,...,922,923,924,925,926,927,928,929,930,931
V12CBD,-0.441694,0.714606,-0.252455,-0.698006,-0.121489,1.791759,0.563874,0.216976,0.496316,1.302225,...,-0.144415,-0.357333,0.696582,-0.406239,-0.594995,0.455246,-0.806654,-0.456271,-0.459923,-0.801339
V15CBD,-0.484454,0.634927,-0.456084,-0.747004,-0.11803,2.183244,0.292293,0.005546,0.482427,1.301236,...,-0.19557,-0.2182,0.890093,-0.538219,-0.681348,0.78801,-0.861559,-0.10991,-0.252345,-0.888362
V59CBD,-0.433886,0.676245,-0.35445,-0.732276,-0.067767,2.447251,0.513434,-0.05507,0.519604,1.091963,...,-0.142337,-0.244578,0.875527,-0.620314,-0.614889,0.499767,-0.83293,-0.282153,-0.3256,-0.840314
V75CBD,-0.430053,0.617852,-0.621162,-0.723635,-0.185876,2.230853,0.119042,-0.190244,0.378296,0.896653,...,-0.170078,-0.257523,1.084113,-0.622394,-0.636057,0.743298,-0.864376,-0.182146,-0.290499,-0.897849
V77CBD,-0.463378,0.671104,-0.220649,-0.812894,-0.181127,2.063128,0.704712,0.135509,0.330133,1.244117,...,-0.173842,-0.240286,0.895598,-0.64339,-0.598937,0.385805,-0.830376,-0.392441,-0.38676,-0.812856
V96CBD,-0.363495,0.618154,-0.240221,-0.683399,-0.171871,2.296653,0.315205,-0.027883,0.388409,1.084987,...,-0.17252,-0.266806,0.851603,-0.567453,-0.623087,0.556548,-0.82959,-0.358175,-0.354244,-0.817816
V99CBD,-0.463216,0.73347,-0.401284,-0.685755,-0.11666,1.503171,0.365917,-0.106233,0.583055,1.391821,...,-0.228818,-0.435935,0.665364,-0.333447,-0.674632,0.438203,-0.802384,-0.294021,-0.445373,-0.84367
V100CBD,-0.385556,0.459241,0.540668,-0.553625,-0.19035,2.566788,0.883203,0.329547,0.396038,1.403423,...,-0.170481,-0.522289,0.898696,-0.370671,-0.700212,0.636703,-0.841154,-0.424055,-0.380434,-0.730314
V12DMSO,-0.418532,0.68618,-0.168602,-0.68328,-0.111069,1.735999,0.568176,0.157265,0.473853,1.451995,...,-0.174411,-0.272481,0.624036,-0.378707,-0.532824,0.420372,-0.785771,-0.449246,-0.434901,-0.779772
V15DMSO,-0.488771,0.649902,-0.51672,-0.741657,-0.171846,2.418734,0.24238,0.004106,0.525163,1.230885,...,-0.195447,-0.146278,1.140006,-0.664448,-0.772246,1.052213,-0.894276,-0.084142,-0.102448,-0.946178
V59DMSO,-0.432547,0.679958,-0.221221,-0.69266,-0.071897,1.908806,0.564367,0.018475,0.534427,1.334628,...,-0.183095,-0.25327,0.652324,-0.441856,-0.54627,0.460744,-0.799942,-0.379429,-0.391427,-0.79783
V75DMSO,-0.448711,0.651573,-0.430325,-0.702486,-0.134777,2.012751,0.291894,0.01241,0.448259,1.305088,...,-0.202911,-0.23811,0.768273,-0.490875,-0.590364,0.622023,-0.821542,-0.272515,-0.325013,-0.814017
V77DMSO,-0.427622,0.664913,-0.150338,-0.674849,-0.121387,1.839942,0.482421,0.009606,0.487649,1.331234,...,-0.177426,-0.269186,0.653342,-0.35218,-0.527622,0.450414,-0.782501,-0.423555,-0.430252,-0.774548
V96DMSO,-0.421336,0.642512,-0.166023,-0.664535,-0.11564,1.819769,0.522553,0.152318,0.481725,1.497902,...,-0.183236,-0.251215,0.614042,-0.372539,-0.524366,0.445288,-0.780172,-0.436325,-0.412542,-0.75816
V99DMSO,-0.425136,0.6476,-0.153687,-0.674022,-0.109129,1.761637,0.527055,0.151553,0.485571,1.492487,...,-0.215679,-0.251467,0.636113,-0.376489,-0.539423,0.425279,-0.776929,-0.425256,-0.43045,-0.766335
V100DMSO,-0.417278,0.650291,-0.081812,-0.661928,-0.142228,1.749156,0.662269,0.235985,0.420544,1.282202,...,-0.118409,-0.267439,0.645533,-0.401672,-0.51948,0.446419,-0.793012,-0.433765,-0.419433,-0.785286

data2

In [84]:
y_new_pred = model.predict(data3)

In [85]:
y_new_pred_df = pd.DataFrame(y_new_pred)

In [86]:
remaining_rows2= remaining_rows.T

In [87]:
remaining_rows2

rid,217398_x_at,1007_s_at,121_at,200617_at,200636_s_at,200666_s_at,200698_at,200757_s_at,200843_s_at,200887_s_at,...,AFFX-r2-Ec-bioD-3_at,AFFX-r2-Ec-bioD-5_at,AFFX-r2-P1-cre-3_at,AFFX-r2-P1-cre-5_at,AFFX-ThrX-3_at,AFFX-ThrX-5_at,AFFX-ThrX-M_at,AFFX-TrpnX-3_at,AFFX-TrpnX-5_at,AFFX-TrpnX-M_at
cid,,,,,,,,,,,,,,,,,,,,,
BSM_0001_PRE-B-I,14.8059,9.1706,7.9557,7.5098,5.5270,9.1653,7.0054,6.8819,9.5021,9.2685,...,4.7895,4.2849,4.2850,4.2851,4.2852,4.5785,4.5270,4.2853,4.6450,4.2855
BSM_0001_PRE-B-I_1,14.8059,9.1706,7.9557,7.5098,5.5270,9.1653,7.0054,6.8819,9.5021,9.2685,...,4.7895,4.2849,4.2850,4.2851,4.2852,4.5785,4.5270,4.2853,4.6450,4.2855
BSM_0002_IMMATURE,14.8277,7.8624,8.4751,7.4879,5.2127,9.0292,7.0383,6.9146,10.4436,9.1952,...,4.6768,4.2507,4.2508,4.2509,4.3711,4.2510,4.7577,4.2511,4.2512,4.2513
BSM_0002_IMMATURE_1,14.8277,7.8624,8.4751,7.4879,5.2127,9.0292,7.0383,6.9146,10.4436,9.1952,...,4.6768,4.2507,4.2508,4.2509,4.3711,4.2510,4.7577,4.2511,4.2512,4.2513
BSM_0003_PRE-B-IISMALL,14.0744,8.7313,8.2574,7.7250,4.9855,8.5248,6.8986,6.3187,8.5869,9.8650,...,5.4943,4.2843,4.2844,4.2845,4.2846,4.2847,4.2848,4.5996,4.6676,4.2849
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
BSM_JOS2724,7.9939,9.7406,9.7397,5.5333,9.7338,12.7129,11.0125,8.7789,14.0234,11.0640,...,13.9672,12.7632,14.9726,14.9335,5.1971,4.2036,4.6807,4.3881,5.0963,4.8404
BSM_JOS2798,9.6896,9.7056,8.9569,6.8455,9.3344,9.7526,10.3173,7.6670,13.9445,11.6169,...,13.9166,13.6866,14.9767,14.9595,4.2278,4.7711,4.5941,4.1927,5.0991,4.2728
BSM_JOS2914,9.5286,13.5666,10.4389,7.0808,6.8337,9.1177,7.5889,5.7576,10.7827,10.5719,...,14.9690,14.9610,14.9845,14.9814,4.3463,4.1513,5.0919,4.1613,5.3533,5.2145
BSM_JOS2915,9.0812,13.4711,10.4054,5.1134,6.3450,6.8628,8.6802,5.6505,8.3866,11.8220,...,14.9767,14.9790,14.9845,14.9814,4.6429,4.1468,4.1185,4.2743,4.4727,4.4593
BSM_JOS2924,9.2025,9.9844,10.0481,7.7709,9.4371,14.5026,10.5512,8.1379,12.7926,12.8906,...,14.7797,14.6965,14.9552,14.9284,4.2412,4.1959,5.1509,4.6052,4.2012,4.7136

In [88]:
y_new_pred_df

,0,1,2,3,4,5,6,7,8,9,...,22258,22259,22260,22261,22262,22263,22264,22265,22266,22267
0,-0.441793,0.714451,-0.252369,-0.697919,-0.121464,1.791892,0.563846,0.216951,0.496242,1.302192,...,24.953396,26.709142,21.799065,21.550833,30.239471,21.507670,27.712241,21.190885,19.695020,20.866133
1,-0.484567,0.634775,-0.455996,-0.746914,-0.118003,2.183367,0.292266,0.005520,0.482351,1.301201,...,24.635780,26.416694,21.517741,21.220122,30.179703,21.366557,27.651946,21.009305,19.569385,20.703168
2,-0.433990,0.676091,-0.354359,-0.732191,-0.067739,2.447378,0.513412,-0.055097,0.519529,1.091925,...,25.114535,26.786010,21.860945,21.659214,30.335898,21.516835,27.788458,20.994815,19.566964,20.714013
3,-0.430160,0.617700,-0.621076,-0.723547,-0.185850,2.230974,0.119014,-0.190268,0.378220,0.896618,...,24.807704,26.448540,21.524983,21.322396,30.329637,21.499038,27.805148,21.083165,19.608361,20.747568
4,-0.463483,0.670953,-0.220561,-0.812807,-0.181102,2.063255,0.704689,0.135486,0.330061,1.244077,...,24.840923,26.397063,21.546121,21.387842,30.340072,21.560773,27.811197,21.210074,19.722018,20.815204
5,-0.363597,0.618000,-0.240132,-0.683314,-0.171845,2.296780,0.315181,-0.027907,0.388335,1.084950,...,24.993405,26.575253,21.638008,21.472912,30.345296,21.537800,27.808152,21.140381,19.694597,20.801567
6,-0.463316,0.733322,-0.401199,-0.685667,-0.116637,1.503307,0.365887,-0.106259,0.582978,1.391787,...,25.051223,26.919306,22.068849,21.759828,30.084917,21.416695,27.622787,21.112721,19.665428,20.824986
7,-0.385664,0.459093,0.540759,-0.553542,-0.190327,2.566911,0.883182,0.329523,0.395967,1.403385,...,24.565080,26.149687,21.144931,20.927615,30.360963,21.561784,27.727967,21.505814,19.951993,21.113099
8,-0.418632,0.686026,-0.168511,-0.683193,-0.111042,1.736134,0.568150,0.157237,0.473778,1.451960,...,25.049271,26.729702,21.886892,21.687053,30.330702,21.506772,27.775268,21.145551,19.699912,20.802746
9,-0.488891,0.649750,-0.516630,-0.741564,-0.171818,2.418850,0.242353,0.004081,0.525086,1.230850,...,24.304498,26.089040,21.072771,20.754450,30.125918,21.291554,27.588533,21.043121,19.612592,20.761026
10,-0.432648,0.679805,-0.221129,-0.692575,-0.071868,1.908940,0.564342,0.018446,0.534351,1.334593,...,25.139933,26.832326,21.963545,21.763157,30.353646,21.519941,27.798860,21.058166,19.624941,20.743464
11,-0.448817,0.651420,-0.430236,-0.702397,-0.134749,2.012879,0.291866,0.012384,0.448183,1.305054,...,24.929740,26.646573,21.768148,21.532234,30.315403,21.472840,27.773678,21.144997,19.697538,20.810238
12,-0.427722,0.664761,-0.150247,-0.674763,-0.121360,1.840078,0.482395,0.009578,0.487574,1.331199,...,25.067020,26.721578,21.883404,21.698873,30.354862,21.510868,27.794797,21.142114,19.700025,20.784479
13,-0.421434,0.642359,-0.165930,-0.664450,-0.115613,1.819905,0.522526,0.152290,0.481649,1.497868,...,25.025023,26.702078,21.829131,21.631036,30.356874,21.526112,27.797639,21.157872,19.726950,20.812064
14,-0.425235,0.647447,-0.153594,-0.673937,-0.109101,1.761774,0.527029,0.151524,0.485495,1.492452,...,25.020217,26.690143,21.847358,21.656681,30.364427,21.533392,27.812126,21.132843,19.702073,20.792716
15,-0.417378,0.650139,-0.081721,-0.661841,-0.142202,1.749290,0.662244,0.235958,0.420470,1.282167,...,24.935920,26.574712,21.713649,21.533394,30.386580,21.550800,27.813866,21.168800,19.726365,20.816970

In [89]:
y_new_pred_df.columns = df.iloc[:, 932:].columns

In [92]:
data.iloc[:, 3:].columns

Index(['ID', 'id', 'V12CBD', 'V15CBD', 'V59CBD', 'V75CBD', 'V77CBD', 'V96CBD',
       'V99CBD', 'V100CBD', 'V12DMSO', 'V15DMSO', 'V59DMSO', 'V75DMSO',
       'V77DMSO', 'V96DMSO', 'V99DMSO', 'V100DMSO'],
      dtype='object')

In [93]:
y_new_pred_df.index = data.iloc[:, 5:].columns

In [ ]:
y_new_pred_df.to_csv('../step3/pre_final.csv')